# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


baseurl: "/Notes" # the subpath of your site, e.g. /blog
url: "https://morgenman.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

#######################################################################
# Settings related to the Header and your About page go here,such as 
# your name, site name, profile pic, site tagline, your bio, 
# your social media links etc
#######################################################################

heading: Cole's Notes # Change this 
copyright:  
  year: 2021
  msg: Dylan Cole Morgen # This is a mandatory attribute for copyright to be displayed ; If deleting this, edit at footer layout.


#####################################################################
# Settings related to your preferences go here, such as the
# search results, wiki-style-links, sidenotes, marginnotes, 
# transclusion, pagepreview, backlinks, related posts, highlighting, 
# context menu, flashcards, sliding window, wrapping
#####################################################################
preferences:
  search:
    enabled: true
    shortcut_hint: 
        enabled: true
  wiki_style_link: # This property handles wiki style links '[['
    enabled: true
  sidenotes: 
    enabled: true
  transclusion:
    enabled: true
  image:
    enabled: true
  pagepreview:
    enabled: true
  highlighting:
    enabled: true
    color: DAEDFF # Takes hexadecimal and basic names like white, red, etc. 
                  # Do not add '#'(the pound symbol) before the hexadecimal number.
                  # In yml, it is considered as a comment
  backlinks:
    enabled: true
  related:
    enabled: false # This enables the posts that are related to each other by tags
  wrapping:
    enabled: true
  contextmenu:
    enabled: false #Not supported in NotesGadern theme
    copylink: 
      enabled: false
    newtab: 
      enabled: false
    backlinks: 
      enabled: false
    related: 
      enabled: false
  flashcards:
    enabled: false #Not supported in NotesGadern theme
  homepage: 
    enabled: true ##If you need a homepage, change this to true and edit _includes/Homepage.html

encoding: utf-8

# Build settings
# theme: null
remote_theme: pages-themes/midnight
plugins:
  - jekyll-feed 
  - jekyll-sitemap 
  - jekyll-tidy
  - jekyll-remote-theme

## Enable _notes Collection 
collections:
    notes:
      output: true
      permalink: /notes/:title      
# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    ## Disabled for NotesGarden Theme. 
    shortname: 

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  math_engine: katex
  smart_quotes: ["apos", "apos", "quot", "quot"]
  syntax_highlighter: rouge
  
sass:
  style: compressed

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: Post
      permalink: /posts/:title
      content-type: post
  - scope:
      path: "_notes"
      type: notes
    values:
      layout: Post
      content-type: notes


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/