[mdzk]
backlinks-header = "Backlinks"
authors = ["morgenman"]
language = "en"
multilingual = false
src = "notes"
title = "Zettelkasten"
ignore = [
    "templates/",
    ".obsidian/",
    "assets/",
    "./404.md"
]

[build]
preprocessors = ["toc"]

[output.html]
copy-fonts = false
no-section-label = true

[output.html.fold]
enable = true
