name: Publish

on:
  push:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          ref: brain

      - name: git stuff
        run: git clone "https://github.com/morgenman/Computer-Science.git" _notes/

      - name: remove .git
        run: rm -r ./_notes/.git
 
      - name: remove github
        run: rm -r ./_notes/.github 
 
      - name: remove obsidian
        run: rm -r ./_notes/.obsidian 
        
      - name: Fix _index page links
        run: find ./_notes/ -name '_*.md' | while read -r i; do  x=`sed -E "s~[[][[](.*)\|(.*)]]~[[\2]]~g" "$i"` && echo "$x" > "$i"; done
          
      - name: Fix Images/Attachments
        run: |
          mkdir ./notes/assets/
          find ./_notes/ -type f -not -name '*.md' -exec mv {} ./notes/assets/ \;
          find ./_notes/ -name '*.md' | while read -r i; do  x=`sed -E "s~![[][[]([^.]*)\.(png|jpg|svg)]]~<a href=\"https://morgenman.github.io/Computer-Science/assets/\1.\2\" target=\"_blank\"><img src=\"https://morgenman.github.io/Computer-Science/assets/\1.\2\" alt=\"\1\"/></a>\n~g" "$i"` && echo "$x" > "$i"; done
          find ./_notes/ -name '*.md' | while read -r i; do  x=`sed -E "s|!*[[][[]([^.]*)\.([^]]*)]]|<a href=\"https://morgenman.github.io/Computer-Science/assets/\1.\2\">\1.\2</a>\n|g" "$i"` && echo "$x" > "$i"; done

      - name: Fix Tables not being rendered correctly
        run: find ./_notes/ -name '*.md' | while read -r i; do  x=`sed -E -z 's/([^|])\n\|/\1\n\n|/g' "$i"` && echo "$x" > "$i"; done
        
      - name: Fix Preprocessor _ handling so it doesn't break math
        run: find ./_notes/ -name '*.md' | while read -r i; do  x=`sed -E 's~([^\$]*)[\$]([^\$]*)\*([^\$]*)[\$]~\1$\2\\\star\3$~g' "$i"` && echo "$x" > "$i"; done
        
      - name: Fix [[Reference#Section]] links
        run: find ./_notes/ -name '*.md' | while read -r i; do  x=`sed -E 's~[!*][[][[]([^#]+)#([^]]*)]]~<a href=\"\1#\l\2\">\1#\2</a>~g' "$i"` && echo "$x" > "$i"; done
                  
      - name: Remove unsupported ! preview
        run: find ./_notes/ -name '*.md' | while read -r i; do  x=`sed -E "s|![[][[]|[[|g" "$i"` && echo "$x" > "$i"; done      
          
      - name: Fix horizontal lines deleting content
        run: find ./_notes/ -name '*.md' | while read -r i; do  x=`sed -E "s|---\$|\n<hr>\n|g" "$i"` && echo "$x" > "$i"; done  
        
      - name: Force linebreaks where lines are broken 
        run: find ./_notes/ -name '*.md' | while read -r i; do  x=`sed -E "s|([.]*)\$|\1  |g" "$i"` && echo "$x" > "$i"; done  
        
      - name: fix first line note being rendered
        run: find ./_notes/ -name '*.md' | while read -r i; do  x=`echo -e "\n"; cat "$i"` && echo "$x" > "$i"; done
  
      - name: copy my notes over
        run: cp -a ./_notes/. ./notes/

      - name: permissions
        run: chmod +x ./mdzk

      - name: Build ZK
        run: ./mdzk build 

      - name: Fix redirection
        run: cp ./html/index.html ./html/index.htm

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html

      - name: Publish
        uses: s0/git-publish-subdir-action@develop 
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: ./
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
